import type { DemoAdminSnapshot } from './types';

const snapshot = {
  generatedLabel: 'Демонстрационный срез · июль 2026',
  kpis: { revenue: 486320, orders: 64, averageOrder: 7599, conversion: 3.8 },
  revenueSeries: [
    { label: 'Пн', revenue: 48200 },
    { label: 'Вт', revenue: 63100 },
    { label: 'Ср', revenue: 57400 },
    { label: 'Чт', revenue: 79900 },
    { label: 'Пт', revenue: 88620 },
    { label: 'Сб', revenue: 91200 },
    { label: 'Вс', revenue: 57800 },
  ],
  products: [
    {
      id: 'p1',
      name: 'RITM White Tee Oversize',
      sku: 'RITM-TEE-WHT-OS-M',
      category: 'Футболки',
      price: 3990,
      stock: 18,
      active: true,
    },
    {
      id: 'p2',
      name: 'RITM Soft Hoodie',
      sku: 'RITM-HOOD-SOFT-GRY-M',
      category: 'Худи',
      price: 8990,
      stock: 9,
      active: true,
    },
    {
      id: 'p3',
      name: 'RITM Clay Overshirt',
      sku: 'RITM-SHIRT-CLAY-L',
      category: 'Рубашки',
      price: 10990,
      stock: 6,
      active: true,
    },
    {
      id: 'p4',
      name: 'RITM Navy Trousers',
      sku: 'RITM-TR-NAVY-M',
      category: 'Брюки',
      price: 8490,
      stock: 4,
      active: true,
    },
    {
      id: 'p5',
      name: 'RITM Black Core Tee',
      sku: 'RITM-TEE-CORE-BLK-M',
      category: 'Футболки',
      price: 3490,
      stock: 22,
      active: true,
    },
    {
      id: 'p6',
      name: 'RITM Sage Zip Hoodie',
      sku: 'RITM-HOOD-ZIP-SAGE-L',
      category: 'Худи',
      price: 8990,
      stock: 0,
      active: false,
    },
  ],
  customers: [
    {
      id: 'c1',
      name: 'Алина Морозова',
      email: 'alina@portfolio.invalid',
      orderCount: 3,
      totalSpent: 24970,
      registeredLabel: '12 июня 2026',
    },
    {
      id: 'c2',
      name: 'Максим Орлов',
      email: 'maxim@portfolio.invalid',
      orderCount: 2,
      totalSpent: 14980,
      registeredLabel: '21 июня 2026',
    },
    {
      id: 'c3',
      name: 'София Белова',
      email: 'sofia@portfolio.invalid',
      orderCount: 4,
      totalSpent: 37160,
      registeredLabel: '2 июля 2026',
    },
  ],
  orders: [
    {
      id: 'o1',
      number: 'RITM-1048',
      customerId: 'c1',
      customerName: 'Алина Морозова',
      status: 'PROCESSING',
      totalAmount: 12980,
      createdLabel: 'Сегодня, 11:24',
    },
    {
      id: 'o2',
      number: 'RITM-1047',
      customerId: 'c2',
      customerName: 'Максим Орлов',
      status: 'SHIPPED',
      totalAmount: 8990,
      createdLabel: 'Сегодня, 09:16',
    },
    {
      id: 'o3',
      number: 'RITM-1046',
      customerId: 'c3',
      customerName: 'София Белова',
      status: 'DELIVERED',
      totalAmount: 19480,
      createdLabel: 'Вчера, 18:42',
    },
    {
      id: 'o4',
      number: 'RITM-1045',
      customerId: 'c1',
      customerName: 'Алина Морозова',
      status: 'PENDING',
      totalAmount: 3990,
      createdLabel: 'Вчера, 15:08',
    },
    {
      id: 'o5',
      number: 'RITM-1044',
      customerId: 'c2',
      customerName: 'Максим Орлов',
      status: 'CANCELLED',
      totalAmount: 5990,
      createdLabel: '10 июля, 13:31',
    },
    {
      id: 'o6',
      number: 'RITM-1043',
      customerId: 'c3',
      customerName: 'София Белова',
      status: 'DELIVERED',
      totalAmount: 17680,
      createdLabel: '9 июля, 17:04',
    },
  ],
  coupons: [
    { id: 'cp1', code: 'RITM10', percent: 10, active: true, expiresLabel: 'Без срока' },
    { id: 'cp2', code: 'WELCOME15', percent: 15, active: true, expiresLabel: '31 декабря 2026' },
    { id: 'cp3', code: 'ARCHIVE20', percent: 20, active: false, expiresLabel: '30 июня 2026' },
  ],
} as const satisfies DemoAdminSnapshot;

export function getDemoAdminSnapshot(): Readonly<DemoAdminSnapshot> {
  return snapshot;
}
